## Importing Dependencies

In [3]:
import numpy as np
import pandas as pd
from numpy import genfromtxt

## Reading Data

In [2]:
data= genfromtxt('bank_note_data.txt',delimiter=',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [11]:
# labels / target   4th column
labels=data[:,4]

In [12]:
# separating the features  --  first four columns
features=data[:,0:4]

In [13]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [15]:
X=features
y=labels

## Spliting the Dataset

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
X_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [18]:
y_train

array([0., 0., 1., ..., 1., 1., 1.])

## Standardization of the Data

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
scalar_object= MinMaxScaler()

In [31]:
scaled_X_train=scalar_object.fit_transform(X_train)

In [32]:
scaled_X_train

array([[4.07704678e-01, 9.83199063e-01, 2.56697443e-01, 9.33178971e-02],
       [7.07908761e-01, 7.71971248e-01, 1.80872580e-01, 8.05140280e-01],
       [1.98559159e-01, 2.21136252e-01, 7.37428144e-01, 6.20911798e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [33]:
X_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [34]:
scaled_X_test=scalar_object.fit_transform(X_test)

In [35]:
scaled_X_test

array([[0.65576832, 0.76019778, 0.24484009, 0.52394294],
       [0.51021119, 0.83150383, 0.1032605 , 0.51241232],
       [0.53621584, 0.78751834, 0.15506107, 0.45135977],
       ...,
       [0.8049803 , 0.34220013, 0.42357773, 0.77514695],
       [0.51021277, 0.83150383, 0.1032605 , 0.51241232],
       [0.7514342 , 0.93958965, 0.08295672, 0.3285983 ]])

In [37]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.4626  , -4.449   ,  3.5427  ,  0.15429 ],
       [-0.278   ,  8.1881  , -3.1338  , -2.5276  ],
       [ 2.7831  , 10.9796  , -3.557   , -4.4039  ]])

## Building the Neural Network

In [73]:
from keras.models import Sequential
from keras.layers import Dense

In [74]:
model =Sequential()

# first hidden layer
model.add(Dense(8, input_dim=4, activation='relu'))

# second hidden layer
model.add(Dense(64, activation='relu'))

# output layer
model.add(Dense(1, activation='sigmoid'))

In [75]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [89]:
model.fit(scaled_X_train, y_train, epochs=70, verbose=1)

Epoch 1/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9816 - loss: 0.0544
Epoch 2/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9843 - loss: 0.0458
Epoch 3/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9889 - loss: 0.0447
Epoch 4/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9757 - loss: 0.0518
Epoch 5/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9922 - loss: 0.0362
Epoch 6/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9865 - loss: 0.0417
Epoch 7/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9813 - loss: 0.0417
Epoch 8/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9866 - loss: 0.0355
Epoch 9/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9854 - loss: 0.0405
Epoch 10/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9913 - loss: 0.0386
Epoch 11/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9846 - loss: 0.0338
Epoch 12/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9877 - lo

35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0193
Epoch 70/70
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9995 - loss: 0.0171


In [90]:
scaled_X_test

array([[0.65576832, 0.76019778, 0.24484009, 0.52394294],
       [0.51021119, 0.83150383, 0.1032605 , 0.51241232],
       [0.53621584, 0.78751834, 0.15506107, 0.45135977],
       ...,
       [0.8049803 , 0.34220013, 0.42357773, 0.77514695],
       [0.51021277, 0.83150383, 0.1032605 , 0.51241232],
       [0.7514342 , 0.93958965, 0.08295672, 0.3285983 ]])

## Predictions

In [91]:
prediction=model.predict(scaled_X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [92]:
prediction

array([[7.67197162e-06],
       [1.60441063e-02],
       [1.56119757e-03],
       [1.78042956e-06],
       [6.56518341e-06],
       [4.04172988e-06],
       [8.14324085e-06],
       [1.74033744e-06],
       [3.41369332e-06],
       [2.33592755e-06],
       [7.17133462e-01],
       [9.98036146e-01],
       [2.73452974e-06],
       [7.84328520e-01],
       [1.15855464e-05],
       [4.81150597e-01],
       [9.27295804e-01],
       [9.53190565e-01],
       [7.82847404e-01],
       [2.15620816e-01],
       [4.19242178e-06],
       [1.61140429e-06],
       [4.14790571e-01],
       [1.63013169e-06],
       [9.99943018e-01],
       [2.01477951e-06],
       [4.02989571e-07],
       [8.84656191e-01],
       [7.59721814e-08],
       [1.91688514e-07],
       [9.97135937e-01],
       [4.32854358e-06],
       [1.26276536e-05],
       [9.99929667e-01],
       [9.99712944e-01],
       [8.28342252e-07],
       [6.01506472e-01],
       [9.87780809e-01],
       [9.98664677e-01],
       [2.83685995e-06],


In [93]:
prediction_class=np.where(prediction>0.5,1,0)

In [94]:
prediction_class

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

## Model Performance

In [95]:
model.metrics_names

['loss', 'compile_metrics']

In [96]:
model.evaluate(scaled_X_test,y_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9467 - loss: 0.0930 


[0.08536830544471741, 0.9563636183738708]

## Classification Report and Confusion Matrix

In [97]:
from sklearn.metrics import classification_report,confusion_matrix

In [98]:
confusion_matrix(y_test,prediction_class)

array([[148,   0],
       [ 12, 115]], dtype=int64)

In [99]:
print(classification_report(y_test,prediction_class))

              precision    recall  f1-score   support

         0.0       0.93      1.00      0.96       148
         1.0       1.00      0.91      0.95       127

    accuracy                           0.96       275
   macro avg       0.96      0.95      0.96       275
weighted avg       0.96      0.96      0.96       275

